### ISSUE TITLE
`loading="lazy"` on the `<figure>` instead of the `<img>`

### ISSUE THREAD

**Issue by borisschapira** [nhoizey/jekyll-cloudinary#50]
When a caption is provided, using `loading="lazy"` applies `loading="lazy"` on the `<figure>`, instead of the `<img>`.

**Comment by borisschapira** [comment]
Fixed by 72d4e6ef7f028b91f349ef66f7f7a58e1b8bb834. Any reason why this as not be pushed to a new version of the gem?

**Comment by nhoizey** [comment]
I'm trying to figure out why https://github.com/nhoizey/jekyll-cloudinary/commit/72d4e6ef7f028b91f349ef66f7f7a58e1b8bb834 doesn't fix it, as it has actually been included in v1.14.0

**Comment by nhoizey** [comment]
Well, it looks indeed that the fix is in the 1.14.0 tag, but was not in the released gem… 🤷‍♂️

**Comment by nhoizey** [comment]
Fixed with release 1.14.1
